<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Paylocity\Api\Normalizer;

use Symfony\Component\Serializer\Exception\InvalidArgumentException;
use Symfony\Component\Serializer\Normalizer\DenormalizerAwareInterface;
use Symfony\Component\Serializer\Normalizer\DenormalizerAwareTrait;
use Symfony\Component\Serializer\Normalizer\DenormalizerInterface;
use Symfony\Component\Serializer\Normalizer\NormalizerAwareInterface;
use Symfony\Component\Serializer\Normalizer\NormalizerAwareTrait;
use Symfony\Component\Serializer\Normalizer\NormalizerInterface;

class EmployeeWorkAddressNormalizer implements DenormalizerInterface, NormalizerInterface, DenormalizerAwareInterface, NormalizerAwareInterface
{
    use DenormalizerAwareTrait;
    use NormalizerAwareTrait;

    public function supportsDenormalization($data, $type, $format = null)
    {
        return $type === 'Paylocity\\Api\\Model\\EmployeeWorkAddress';
    }

    public function supportsNormalization($data, $format = null)
    {
        return get_class($data) === 'Paylocity\\Api\\Model\\EmployeeWorkAddress';
    }

    public function denormalize($data, $class, $format = null, array $context = [])
    {
        if (!is_object($data)) {
            throw new InvalidArgumentException();
        }
        $object = new \Paylocity\Api\Model\EmployeeWorkAddress();
        if (property_exists($data, 'address1')) {
            $value = $data->{'address1'};
            if (is_string($data->{'address1'})) {
                $value = $data->{'address1'};
            } elseif (is_null($data->{'address1'})) {
                $value = $data->{'address1'};
            }
            $object->setAddress1($value);
        }
        if (property_exists($data, 'address2')) {
            $value_1 = $data->{'address2'};
            if (is_string($data->{'address2'})) {
                $value_1 = $data->{'address2'};
            } elseif (is_null($data->{'address2'})) {
                $value_1 = $data->{'address2'};
            }
            $object->setAddress2($value_1);
        }
        if (property_exists($data, 'city')) {
            $value_2 = $data->{'city'};
            if (is_string($data->{'city'})) {
                $value_2 = $data->{'city'};
            } elseif (is_null($data->{'city'})) {
                $value_2 = $data->{'city'};
            }
            $object->setCity($value_2);
        }
        if (property_exists($data, 'country')) {
            $value_3 = $data->{'country'};
            if (is_string($data->{'country'})) {
                $value_3 = $data->{'country'};
            } elseif (is_null($data->{'country'})) {
                $value_3 = $data->{'country'};
            }
            $object->setCountry($value_3);
        }
        if (property_exists($data, 'county')) {
            $value_4 = $data->{'county'};
            if (is_string($data->{'county'})) {
                $value_4 = $data->{'county'};
            } elseif (is_null($data->{'county'})) {
                $value_4 = $data->{'county'};
            }
            $object->setCounty($value_4);
        }
        if (property_exists($data, 'emailAddress')) {
            $value_5 = $data->{'emailAddress'};
            if (is_string($data->{'emailAddress'})) {
                $value_5 = $data->{'emailAddress'};
            } elseif (is_null($data->{'emailAddress'})) {
                $value_5 = $data->{'emailAddress'};
            }
            $object->setEmailAddress($value_5);
        }
        if (property_exists($data, 'location')) {
            $value_6 = $data->{'location'};
            if (is_string($data->{'location'})) {
                $value_6 = $data->{'location'};
            } elseif (is_null($data->{'location'})) {
                $value_6 = $data->{'location'};
            }
            $object->setLocation($value_6);
        }
        if (property_exists($data, 'mailStop')) {
            $value_7 = $data->{'mailStop'};
            if (is_string($data->{'mailStop'})) {
                $value_7 = $data->{'mailStop'};
            } elseif (is_null($data->{'mailStop'})) {
                $value_7 = $data->{'mailStop'};
            }
            $object->setMailStop($value_7);
        }
        if (property_exists($data, 'mobilePhone')) {
            $value_8 = $data->{'mobilePhone'};
            if (is_string($data->{'mobilePhone'})) {
                $value_8 = $data->{'mobilePhone'};
            } elseif (is_null($data->{'mobilePhone'})) {
                $value_8 = $data->{'mobilePhone'};
            }
            $object->setMobilePhone($value_8);
        }
        if (property_exists($data, 'pager')) {
            $value_9 = $data->{'pager'};
            if (is_string($data->{'pager'})) {
                $value_9 = $data->{'pager'};
            } elseif (is_null($data->{'pager'})) {
                $value_9 = $data->{'pager'};
            }
            $object->setPager($value_9);
        }
        if (property_exists($data, 'phone')) {
            $value_10 = $data->{'phone'};
            if (is_string($data->{'phone'})) {
                $value_10 = $data->{'phone'};
            } elseif (is_null($data->{'phone'})) {
                $value_10 = $data->{'phone'};
            }
            $object->setPhone($value_10);
        }
        if (property_exists($data, 'phoneExtension')) {
            $value_11 = $data->{'phoneExtension'};
            if (is_string($data->{'phoneExtension'})) {
                $value_11 = $data->{'phoneExtension'};
            } elseif (is_null($data->{'phoneExtension'})) {
                $value_11 = $data->{'phoneExtension'};
            }
            $object->setPhoneExtension($value_11);
        }
        if (property_exists($data, 'postalCode')) {
            $value_12 = $data->{'postalCode'};
            if (is_string($data->{'postalCode'})) {
                $value_12 = $data->{'postalCode'};
            } elseif (is_null($data->{'postalCode'})) {
                $value_12 = $data->{'postalCode'};
            }
            $object->setPostalCode($value_12);
        }
        if (property_exists($data, 'state')) {
            $value_13 = $data->{'state'};
            if (is_string($data->{'state'})) {
                $value_13 = $data->{'state'};
            } elseif (is_null($data->{'state'})) {
                $value_13 = $data->{'state'};
            }
            $object->setState($value_13);
        }

        return $object;
    }

    public function normalize($object, $format = null, array $context = [])
    {
        $data = new \stdClass();
        $value = $object->getAddress1();
        if (is_string($object->getAddress1())) {
            $value = $object->getAddress1();
        } elseif (is_null($object->getAddress1())) {
            $value = $object->getAddress1();
        }
        $data->{'address1'} = $value;
        $value_1 = $object->getAddress2();
        if (is_string($object->getAddress2())) {
            $value_1 = $object->getAddress2();
        } elseif (is_null($object->getAddress2())) {
            $value_1 = $object->getAddress2();
        }
        $data->{'address2'} = $value_1;
        $value_2 = $object->getCity();
        if (is_string($object->getCity())) {
            $value_2 = $object->getCity();
        } elseif (is_null($object->getCity())) {
            $value_2 = $object->getCity();
        }
        $data->{'city'} = $value_2;
        $value_3 = $object->getCountry();
        if (is_string($object->getCountry())) {
            $value_3 = $object->getCountry();
        } elseif (is_null($object->getCountry())) {
            $value_3 = $object->getCountry();
        }
        $data->{'country'} = $value_3;
        $value_4 = $object->getCounty();
        if (is_string($object->getCounty())) {
            $value_4 = $object->getCounty();
        } elseif (is_null($object->getCounty())) {
            $value_4 = $object->getCounty();
        }
        $data->{'county'} = $value_4;
        $value_5 = $object->getEmailAddress();
        if (is_string($object->getEmailAddress())) {
            $value_5 = $object->getEmailAddress();
        } elseif (is_null($object->getEmailAddress())) {
            $value_5 = $object->getEmailAddress();
        }
        $data->{'emailAddress'} = $value_5;
        $value_6 = $object->getLocation();
        if (is_string($object->getLocation())) {
            $value_6 = $object->getLocation();
        } elseif (is_null($object->getLocation())) {
            $value_6 = $object->getLocation();
        }
        $data->{'location'} = $value_6;
        $value_7 = $object->getMailStop();
        if (is_string($object->getMailStop())) {
            $value_7 = $object->getMailStop();
        } elseif (is_null($object->getMailStop())) {
            $value_7 = $object->getMailStop();
        }
        $data->{'mailStop'} = $value_7;
        $value_8 = $object->getMobilePhone();
        if (is_string($object->getMobilePhone())) {
            $value_8 = $object->getMobilePhone();
        } elseif (is_null($object->getMobilePhone())) {
            $value_8 = $object->getMobilePhone();
        }
        $data->{'mobilePhone'} = $value_8;
        $value_9 = $object->getPager();
        if (is_string($object->getPager())) {
            $value_9 = $object->getPager();
        } elseif (is_null($object->getPager())) {
            $value_9 = $object->getPager();
        }
        $data->{'pager'} = $value_9;
        $value_10 = $object->getPhone();
        if (is_string($object->getPhone())) {
            $value_10 = $object->getPhone();
        } elseif (is_null($object->getPhone())) {
            $value_10 = $object->getPhone();
        }
        $data->{'phone'} = $value_10;
        $value_11 = $object->getPhoneExtension();
        if (is_string($object->getPhoneExtension())) {
            $value_11 = $object->getPhoneExtension();
        } elseif (is_null($object->getPhoneExtension())) {
            $value_11 = $object->getPhoneExtension();
        }
        $data->{'phoneExtension'} = $value_11;
        $value_12 = $object->getPostalCode();
        if (is_string($object->getPostalCode())) {
            $value_12 = $object->getPostalCode();
        } elseif (is_null($object->getPostalCode())) {
            $value_12 = $object->getPostalCode();
        }
        $data->{'postalCode'} = $value_12;
        $value_13 = $object->getState();
        if (is_string($object->getState())) {
            $value_13 = $object->getState();
        } elseif (is_null($object->getState())) {
            $value_13 = $object->getState();
        }
        $data->{'state'} = $value_13;

        return $data;
    }
}
