<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Paylocity\Api\Normalizer;

use Symfony\Component\Serializer\Exception\InvalidArgumentException;
use Symfony\Component\Serializer\Normalizer\DenormalizerAwareInterface;
use Symfony\Component\Serializer\Normalizer\DenormalizerAwareTrait;
use Symfony\Component\Serializer\Normalizer\DenormalizerInterface;
use Symfony\Component\Serializer\Normalizer\NormalizerAwareInterface;
use Symfony\Component\Serializer\Normalizer\NormalizerAwareTrait;
use Symfony\Component\Serializer\Normalizer\NormalizerInterface;

class EmployeeDepartmentPositionNormalizer implements DenormalizerInterface, NormalizerInterface, DenormalizerAwareInterface, NormalizerAwareInterface
{
    use DenormalizerAwareTrait;
    use NormalizerAwareTrait;

    public function supportsDenormalization($data, $type, $format = null)
    {
        return $type === 'Paylocity\\Api\\Model\\EmployeeDepartmentPosition';
    }

    public function supportsNormalization($data, $format = null)
    {
        return get_class($data) === 'Paylocity\\Api\\Model\\EmployeeDepartmentPosition';
    }

    public function denormalize($data, $class, $format = null, array $context = [])
    {
        if (!is_object($data)) {
            throw new InvalidArgumentException();
        }
        $object = new \Paylocity\Api\Model\EmployeeDepartmentPosition();
        if (property_exists($data, 'changeReason')) {
            $value = $data->{'changeReason'};
            if (is_string($data->{'changeReason'})) {
                $value = $data->{'changeReason'};
            } elseif (is_null($data->{'changeReason'})) {
                $value = $data->{'changeReason'};
            }
            $object->setChangeReason($value);
        }
        if (property_exists($data, 'clockBadgeNumber')) {
            $value_1 = $data->{'clockBadgeNumber'};
            if (is_string($data->{'clockBadgeNumber'})) {
                $value_1 = $data->{'clockBadgeNumber'};
            } elseif (is_null($data->{'clockBadgeNumber'})) {
                $value_1 = $data->{'clockBadgeNumber'};
            }
            $object->setClockBadgeNumber($value_1);
        }
        if (property_exists($data, 'costCenter1')) {
            $value_2 = $data->{'costCenter1'};
            if (is_string($data->{'costCenter1'})) {
                $value_2 = $data->{'costCenter1'};
            } elseif (is_null($data->{'costCenter1'})) {
                $value_2 = $data->{'costCenter1'};
            }
            $object->setCostCenter1($value_2);
        }
        if (property_exists($data, 'costCenter2')) {
            $value_3 = $data->{'costCenter2'};
            if (is_string($data->{'costCenter2'})) {
                $value_3 = $data->{'costCenter2'};
            } elseif (is_null($data->{'costCenter2'})) {
                $value_3 = $data->{'costCenter2'};
            }
            $object->setCostCenter2($value_3);
        }
        if (property_exists($data, 'costCenter3')) {
            $value_4 = $data->{'costCenter3'};
            if (is_string($data->{'costCenter3'})) {
                $value_4 = $data->{'costCenter3'};
            } elseif (is_null($data->{'costCenter3'})) {
                $value_4 = $data->{'costCenter3'};
            }
            $object->setCostCenter3($value_4);
        }
        if (property_exists($data, 'effectiveDate')) {
            $value_5 = $data->{'effectiveDate'};
            if (is_string($data->{'effectiveDate'})) {
                $value_5 = $data->{'effectiveDate'};
            } elseif (is_null($data->{'effectiveDate'})) {
                $value_5 = $data->{'effectiveDate'};
            }
            $object->setEffectiveDate($value_5);
        }
        if (property_exists($data, 'employeeType')) {
            $value_6 = $data->{'employeeType'};
            if (is_string($data->{'employeeType'})) {
                $value_6 = $data->{'employeeType'};
            } elseif (is_null($data->{'employeeType'})) {
                $value_6 = $data->{'employeeType'};
            }
            $object->setEmployeeType($value_6);
        }
        if (property_exists($data, 'equalEmploymentOpportunityClass')) {
            $value_7 = $data->{'equalEmploymentOpportunityClass'};
            if (is_string($data->{'equalEmploymentOpportunityClass'})) {
                $value_7 = $data->{'equalEmploymentOpportunityClass'};
            } elseif (is_null($data->{'equalEmploymentOpportunityClass'})) {
                $value_7 = $data->{'equalEmploymentOpportunityClass'};
            }
            $object->setEqualEmploymentOpportunityClass($value_7);
        }
        if (property_exists($data, 'isMinimumWageExempt')) {
            $value_8 = $data->{'isMinimumWageExempt'};
            if (is_bool($data->{'isMinimumWageExempt'})) {
                $value_8 = $data->{'isMinimumWageExempt'};
            } elseif (is_null($data->{'isMinimumWageExempt'})) {
                $value_8 = $data->{'isMinimumWageExempt'};
            }
            $object->setIsMinimumWageExempt($value_8);
        }
        if (property_exists($data, 'isOvertimeExempt')) {
            $value_9 = $data->{'isOvertimeExempt'};
            if (is_bool($data->{'isOvertimeExempt'})) {
                $value_9 = $data->{'isOvertimeExempt'};
            } elseif (is_null($data->{'isOvertimeExempt'})) {
                $value_9 = $data->{'isOvertimeExempt'};
            }
            $object->setIsOvertimeExempt($value_9);
        }
        if (property_exists($data, 'isSupervisorReviewer')) {
            $value_10 = $data->{'isSupervisorReviewer'};
            if (is_bool($data->{'isSupervisorReviewer'})) {
                $value_10 = $data->{'isSupervisorReviewer'};
            } elseif (is_null($data->{'isSupervisorReviewer'})) {
                $value_10 = $data->{'isSupervisorReviewer'};
            }
            $object->setIsSupervisorReviewer($value_10);
        }
        if (property_exists($data, 'isUnionDuesCollected')) {
            $value_11 = $data->{'isUnionDuesCollected'};
            if (is_bool($data->{'isUnionDuesCollected'})) {
                $value_11 = $data->{'isUnionDuesCollected'};
            } elseif (is_null($data->{'isUnionDuesCollected'})) {
                $value_11 = $data->{'isUnionDuesCollected'};
            }
            $object->setIsUnionDuesCollected($value_11);
        }
        if (property_exists($data, 'isUnionInitiationCollected')) {
            $value_12 = $data->{'isUnionInitiationCollected'};
            if (is_bool($data->{'isUnionInitiationCollected'})) {
                $value_12 = $data->{'isUnionInitiationCollected'};
            } elseif (is_null($data->{'isUnionInitiationCollected'})) {
                $value_12 = $data->{'isUnionInitiationCollected'};
            }
            $object->setIsUnionInitiationCollected($value_12);
        }
        if (property_exists($data, 'jobTitle')) {
            $value_13 = $data->{'jobTitle'};
            if (is_string($data->{'jobTitle'})) {
                $value_13 = $data->{'jobTitle'};
            } elseif (is_null($data->{'jobTitle'})) {
                $value_13 = $data->{'jobTitle'};
            }
            $object->setJobTitle($value_13);
        }
        if (property_exists($data, 'payGroup')) {
            $value_14 = $data->{'payGroup'};
            if (is_string($data->{'payGroup'})) {
                $value_14 = $data->{'payGroup'};
            } elseif (is_null($data->{'payGroup'})) {
                $value_14 = $data->{'payGroup'};
            }
            $object->setPayGroup($value_14);
        }
        if (property_exists($data, 'positionCode')) {
            $value_15 = $data->{'positionCode'};
            if (is_string($data->{'positionCode'})) {
                $value_15 = $data->{'positionCode'};
            } elseif (is_null($data->{'positionCode'})) {
                $value_15 = $data->{'positionCode'};
            }
            $object->setPositionCode($value_15);
        }
        if (property_exists($data, 'reviewerCompanyNumber')) {
            $value_16 = $data->{'reviewerCompanyNumber'};
            if (is_string($data->{'reviewerCompanyNumber'})) {
                $value_16 = $data->{'reviewerCompanyNumber'};
            } elseif (is_null($data->{'reviewerCompanyNumber'})) {
                $value_16 = $data->{'reviewerCompanyNumber'};
            }
            $object->setReviewerCompanyNumber($value_16);
        }
        if (property_exists($data, 'reviewerEmployeeId')) {
            $value_17 = $data->{'reviewerEmployeeId'};
            if (is_string($data->{'reviewerEmployeeId'})) {
                $value_17 = $data->{'reviewerEmployeeId'};
            } elseif (is_null($data->{'reviewerEmployeeId'})) {
                $value_17 = $data->{'reviewerEmployeeId'};
            }
            $object->setReviewerEmployeeId($value_17);
        }
        if (property_exists($data, 'shift')) {
            $value_18 = $data->{'shift'};
            if (is_string($data->{'shift'})) {
                $value_18 = $data->{'shift'};
            } elseif (is_null($data->{'shift'})) {
                $value_18 = $data->{'shift'};
            }
            $object->setShift($value_18);
        }
        if (property_exists($data, 'supervisorCompanyNumber')) {
            $value_19 = $data->{'supervisorCompanyNumber'};
            if (is_string($data->{'supervisorCompanyNumber'})) {
                $value_19 = $data->{'supervisorCompanyNumber'};
            } elseif (is_null($data->{'supervisorCompanyNumber'})) {
                $value_19 = $data->{'supervisorCompanyNumber'};
            }
            $object->setSupervisorCompanyNumber($value_19);
        }
        if (property_exists($data, 'supervisorEmployeeId')) {
            $value_20 = $data->{'supervisorEmployeeId'};
            if (is_string($data->{'supervisorEmployeeId'})) {
                $value_20 = $data->{'supervisorEmployeeId'};
            } elseif (is_null($data->{'supervisorEmployeeId'})) {
                $value_20 = $data->{'supervisorEmployeeId'};
            }
            $object->setSupervisorEmployeeId($value_20);
        }
        if (property_exists($data, 'tipped')) {
            $value_21 = $data->{'tipped'};
            if (is_string($data->{'tipped'})) {
                $value_21 = $data->{'tipped'};
            } elseif (is_null($data->{'tipped'})) {
                $value_21 = $data->{'tipped'};
            }
            $object->setTipped($value_21);
        }
        if (property_exists($data, 'unionAffiliationDate')) {
            $value_22 = $data->{'unionAffiliationDate'};
            if (is_string($data->{'unionAffiliationDate'})) {
                $value_22 = $data->{'unionAffiliationDate'};
            } elseif (is_null($data->{'unionAffiliationDate'})) {
                $value_22 = $data->{'unionAffiliationDate'};
            }
            $object->setUnionAffiliationDate($value_22);
        }
        if (property_exists($data, 'unionCode')) {
            $value_23 = $data->{'unionCode'};
            if (is_string($data->{'unionCode'})) {
                $value_23 = $data->{'unionCode'};
            } elseif (is_null($data->{'unionCode'})) {
                $value_23 = $data->{'unionCode'};
            }
            $object->setUnionCode($value_23);
        }
        if (property_exists($data, 'unionPosition')) {
            $value_24 = $data->{'unionPosition'};
            if (is_string($data->{'unionPosition'})) {
                $value_24 = $data->{'unionPosition'};
            } elseif (is_null($data->{'unionPosition'})) {
                $value_24 = $data->{'unionPosition'};
            }
            $object->setUnionPosition($value_24);
        }
        if (property_exists($data, 'workersCompensation')) {
            $value_25 = $data->{'workersCompensation'};
            if (is_string($data->{'workersCompensation'})) {
                $value_25 = $data->{'workersCompensation'};
            } elseif (is_null($data->{'workersCompensation'})) {
                $value_25 = $data->{'workersCompensation'};
            }
            $object->setWorkersCompensation($value_25);
        }

        return $object;
    }

    public function normalize($object, $format = null, array $context = [])
    {
        $data = new \stdClass();
        $value = $object->getChangeReason();
        if (is_string($object->getChangeReason())) {
            $value = $object->getChangeReason();
        } elseif (is_null($object->getChangeReason())) {
            $value = $object->getChangeReason();
        }
        $data->{'changeReason'} = $value;
        $value_1 = $object->getClockBadgeNumber();
        if (is_string($object->getClockBadgeNumber())) {
            $value_1 = $object->getClockBadgeNumber();
        } elseif (is_null($object->getClockBadgeNumber())) {
            $value_1 = $object->getClockBadgeNumber();
        }
        $data->{'clockBadgeNumber'} = $value_1;
        $value_2 = $object->getCostCenter1();
        if (is_string($object->getCostCenter1())) {
            $value_2 = $object->getCostCenter1();
        } elseif (is_null($object->getCostCenter1())) {
            $value_2 = $object->getCostCenter1();
        }
        $data->{'costCenter1'} = $value_2;
        $value_3 = $object->getCostCenter2();
        if (is_string($object->getCostCenter2())) {
            $value_3 = $object->getCostCenter2();
        } elseif (is_null($object->getCostCenter2())) {
            $value_3 = $object->getCostCenter2();
        }
        $data->{'costCenter2'} = $value_3;
        $value_4 = $object->getCostCenter3();
        if (is_string($object->getCostCenter3())) {
            $value_4 = $object->getCostCenter3();
        } elseif (is_null($object->getCostCenter3())) {
            $value_4 = $object->getCostCenter3();
        }
        $data->{'costCenter3'} = $value_4;
        $value_5 = $object->getEffectiveDate();
        if (is_string($object->getEffectiveDate())) {
            $value_5 = $object->getEffectiveDate();
        } elseif (is_null($object->getEffectiveDate())) {
            $value_5 = $object->getEffectiveDate();
        }
        $data->{'effectiveDate'} = $value_5;
        $value_6 = $object->getEmployeeType();
        if (is_string($object->getEmployeeType())) {
            $value_6 = $object->getEmployeeType();
        } elseif (is_null($object->getEmployeeType())) {
            $value_6 = $object->getEmployeeType();
        }
        $data->{'employeeType'} = $value_6;
        $value_7 = $object->getEqualEmploymentOpportunityClass();
        if (is_string($object->getEqualEmploymentOpportunityClass())) {
            $value_7 = $object->getEqualEmploymentOpportunityClass();
        } elseif (is_null($object->getEqualEmploymentOpportunityClass())) {
            $value_7 = $object->getEqualEmploymentOpportunityClass();
        }
        $data->{'equalEmploymentOpportunityClass'} = $value_7;
        $value_8 = $object->getIsMinimumWageExempt();
        if (is_bool($object->getIsMinimumWageExempt())) {
            $value_8 = $object->getIsMinimumWageExempt();
        } elseif (is_null($object->getIsMinimumWageExempt())) {
            $value_8 = $object->getIsMinimumWageExempt();
        }
        $data->{'isMinimumWageExempt'} = $value_8;
        $value_9 = $object->getIsOvertimeExempt();
        if (is_bool($object->getIsOvertimeExempt())) {
            $value_9 = $object->getIsOvertimeExempt();
        } elseif (is_null($object->getIsOvertimeExempt())) {
            $value_9 = $object->getIsOvertimeExempt();
        }
        $data->{'isOvertimeExempt'} = $value_9;
        $value_10 = $object->getIsSupervisorReviewer();
        if (is_bool($object->getIsSupervisorReviewer())) {
            $value_10 = $object->getIsSupervisorReviewer();
        } elseif (is_null($object->getIsSupervisorReviewer())) {
            $value_10 = $object->getIsSupervisorReviewer();
        }
        $data->{'isSupervisorReviewer'} = $value_10;
        $value_11 = $object->getIsUnionDuesCollected();
        if (is_bool($object->getIsUnionDuesCollected())) {
            $value_11 = $object->getIsUnionDuesCollected();
        } elseif (is_null($object->getIsUnionDuesCollected())) {
            $value_11 = $object->getIsUnionDuesCollected();
        }
        $data->{'isUnionDuesCollected'} = $value_11;
        $value_12 = $object->getIsUnionInitiationCollected();
        if (is_bool($object->getIsUnionInitiationCollected())) {
            $value_12 = $object->getIsUnionInitiationCollected();
        } elseif (is_null($object->getIsUnionInitiationCollected())) {
            $value_12 = $object->getIsUnionInitiationCollected();
        }
        $data->{'isUnionInitiationCollected'} = $value_12;
        $value_13 = $object->getJobTitle();
        if (is_string($object->getJobTitle())) {
            $value_13 = $object->getJobTitle();
        } elseif (is_null($object->getJobTitle())) {
            $value_13 = $object->getJobTitle();
        }
        $data->{'jobTitle'} = $value_13;
        $value_14 = $object->getPayGroup();
        if (is_string($object->getPayGroup())) {
            $value_14 = $object->getPayGroup();
        } elseif (is_null($object->getPayGroup())) {
            $value_14 = $object->getPayGroup();
        }
        $data->{'payGroup'} = $value_14;
        $value_15 = $object->getPositionCode();
        if (is_string($object->getPositionCode())) {
            $value_15 = $object->getPositionCode();
        } elseif (is_null($object->getPositionCode())) {
            $value_15 = $object->getPositionCode();
        }
        $data->{'positionCode'} = $value_15;
        $value_16 = $object->getReviewerCompanyNumber();
        if (is_string($object->getReviewerCompanyNumber())) {
            $value_16 = $object->getReviewerCompanyNumber();
        } elseif (is_null($object->getReviewerCompanyNumber())) {
            $value_16 = $object->getReviewerCompanyNumber();
        }
        $data->{'reviewerCompanyNumber'} = $value_16;
        $value_17 = $object->getReviewerEmployeeId();
        if (is_string($object->getReviewerEmployeeId())) {
            $value_17 = $object->getReviewerEmployeeId();
        } elseif (is_null($object->getReviewerEmployeeId())) {
            $value_17 = $object->getReviewerEmployeeId();
        }
        $data->{'reviewerEmployeeId'} = $value_17;
        $value_18 = $object->getShift();
        if (is_string($object->getShift())) {
            $value_18 = $object->getShift();
        } elseif (is_null($object->getShift())) {
            $value_18 = $object->getShift();
        }
        $data->{'shift'} = $value_18;
        $value_19 = $object->getSupervisorCompanyNumber();
        if (is_string($object->getSupervisorCompanyNumber())) {
            $value_19 = $object->getSupervisorCompanyNumber();
        } elseif (is_null($object->getSupervisorCompanyNumber())) {
            $value_19 = $object->getSupervisorCompanyNumber();
        }
        $data->{'supervisorCompanyNumber'} = $value_19;
        $value_20 = $object->getSupervisorEmployeeId();
        if (is_string($object->getSupervisorEmployeeId())) {
            $value_20 = $object->getSupervisorEmployeeId();
        } elseif (is_null($object->getSupervisorEmployeeId())) {
            $value_20 = $object->getSupervisorEmployeeId();
        }
        $data->{'supervisorEmployeeId'} = $value_20;
        $value_21 = $object->getTipped();
        if (is_string($object->getTipped())) {
            $value_21 = $object->getTipped();
        } elseif (is_null($object->getTipped())) {
            $value_21 = $object->getTipped();
        }
        $data->{'tipped'} = $value_21;
        $value_22 = $object->getUnionAffiliationDate();
        if (is_string($object->getUnionAffiliationDate())) {
            $value_22 = $object->getUnionAffiliationDate();
        } elseif (is_null($object->getUnionAffiliationDate())) {
            $value_22 = $object->getUnionAffiliationDate();
        }
        $data->{'unionAffiliationDate'} = $value_22;
        $value_23 = $object->getUnionCode();
        if (is_string($object->getUnionCode())) {
            $value_23 = $object->getUnionCode();
        } elseif (is_null($object->getUnionCode())) {
            $value_23 = $object->getUnionCode();
        }
        $data->{'unionCode'} = $value_23;
        $value_24 = $object->getUnionPosition();
        if (is_string($object->getUnionPosition())) {
            $value_24 = $object->getUnionPosition();
        } elseif (is_null($object->getUnionPosition())) {
            $value_24 = $object->getUnionPosition();
        }
        $data->{'unionPosition'} = $value_24;
        $value_25 = $object->getWorkersCompensation();
        if (is_string($object->getWorkersCompensation())) {
            $value_25 = $object->getWorkersCompensation();
        } elseif (is_null($object->getWorkersCompensation())) {
            $value_25 = $object->getWorkersCompensation();
        }
        $data->{'workersCompensation'} = $value_25;

        return $data;
    }
}
