<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Paylocity\Api\Normalizer;

use Symfony\Component\Serializer\Exception\InvalidArgumentException;
use Symfony\Component\Serializer\Normalizer\DenormalizerAwareInterface;
use Symfony\Component\Serializer\Normalizer\DenormalizerAwareTrait;
use Symfony\Component\Serializer\Normalizer\DenormalizerInterface;
use Symfony\Component\Serializer\Normalizer\NormalizerAwareInterface;
use Symfony\Component\Serializer\Normalizer\NormalizerAwareTrait;
use Symfony\Component\Serializer\Normalizer\NormalizerInterface;

class EmployeePrimaryPayRateNormalizer implements DenormalizerInterface, NormalizerInterface, DenormalizerAwareInterface, NormalizerAwareInterface
{
    use DenormalizerAwareTrait;
    use NormalizerAwareTrait;

    public function supportsDenormalization($data, $type, $format = null)
    {
        return $type === 'Paylocity\\Api\\Model\\EmployeePrimaryPayRate';
    }

    public function supportsNormalization($data, $format = null)
    {
        return get_class($data) === 'Paylocity\\Api\\Model\\EmployeePrimaryPayRate';
    }

    public function denormalize($data, $class, $format = null, array $context = [])
    {
        if (!is_object($data)) {
            throw new InvalidArgumentException();
        }
        $object = new \Paylocity\Api\Model\EmployeePrimaryPayRate();
        if (property_exists($data, 'annualSalary')) {
            $value = $data->{'annualSalary'};
            if (is_float($data->{'annualSalary'})) {
                $value = $data->{'annualSalary'};
            } elseif (is_null($data->{'annualSalary'})) {
                $value = $data->{'annualSalary'};
            }
            $object->setAnnualSalary($value);
        }
        if (property_exists($data, 'baseRate')) {
            $value_1 = $data->{'baseRate'};
            if (is_float($data->{'baseRate'})) {
                $value_1 = $data->{'baseRate'};
            } elseif (is_null($data->{'baseRate'})) {
                $value_1 = $data->{'baseRate'};
            }
            $object->setBaseRate($value_1);
        }
        if (property_exists($data, 'beginCheckDate')) {
            $value_2 = $data->{'beginCheckDate'};
            if (is_string($data->{'beginCheckDate'})) {
                $value_2 = $data->{'beginCheckDate'};
            } elseif (is_null($data->{'beginCheckDate'})) {
                $value_2 = $data->{'beginCheckDate'};
            }
            $object->setBeginCheckDate($value_2);
        }
        if (property_exists($data, 'changeReason')) {
            $value_3 = $data->{'changeReason'};
            if (is_string($data->{'changeReason'})) {
                $value_3 = $data->{'changeReason'};
            } elseif (is_null($data->{'changeReason'})) {
                $value_3 = $data->{'changeReason'};
            }
            $object->setChangeReason($value_3);
        }
        if (property_exists($data, 'defaultHours')) {
            $value_4 = $data->{'defaultHours'};
            if (is_float($data->{'defaultHours'})) {
                $value_4 = $data->{'defaultHours'};
            } elseif (is_null($data->{'defaultHours'})) {
                $value_4 = $data->{'defaultHours'};
            }
            $object->setDefaultHours($value_4);
        }
        if (property_exists($data, 'effectiveDate')) {
            $value_5 = $data->{'effectiveDate'};
            if (is_string($data->{'effectiveDate'})) {
                $value_5 = $data->{'effectiveDate'};
            } elseif (is_null($data->{'effectiveDate'})) {
                $value_5 = $data->{'effectiveDate'};
            }
            $object->setEffectiveDate($value_5);
        }
        if (property_exists($data, 'isAutoPay')) {
            $value_6 = $data->{'isAutoPay'};
            if (is_bool($data->{'isAutoPay'})) {
                $value_6 = $data->{'isAutoPay'};
            } elseif (is_null($data->{'isAutoPay'})) {
                $value_6 = $data->{'isAutoPay'};
            }
            $object->setIsAutoPay($value_6);
        }
        if (property_exists($data, 'payFrequency')) {
            $value_7 = $data->{'payFrequency'};
            if (is_string($data->{'payFrequency'})) {
                $value_7 = $data->{'payFrequency'};
            } elseif (is_null($data->{'payFrequency'})) {
                $value_7 = $data->{'payFrequency'};
            }
            $object->setPayFrequency($value_7);
        }
        if (property_exists($data, 'payGrade')) {
            $value_8 = $data->{'payGrade'};
            if (is_string($data->{'payGrade'})) {
                $value_8 = $data->{'payGrade'};
            } elseif (is_null($data->{'payGrade'})) {
                $value_8 = $data->{'payGrade'};
            }
            $object->setPayGrade($value_8);
        }
        if (property_exists($data, 'payRateNote')) {
            $value_9 = $data->{'payRateNote'};
            if (is_string($data->{'payRateNote'})) {
                $value_9 = $data->{'payRateNote'};
            } elseif (is_null($data->{'payRateNote'})) {
                $value_9 = $data->{'payRateNote'};
            }
            $object->setPayRateNote($value_9);
        }
        if (property_exists($data, 'payType')) {
            $value_10 = $data->{'payType'};
            if (is_string($data->{'payType'})) {
                $value_10 = $data->{'payType'};
            } elseif (is_null($data->{'payType'})) {
                $value_10 = $data->{'payType'};
            }
            $object->setPayType($value_10);
        }
        if (property_exists($data, 'ratePer')) {
            $value_11 = $data->{'ratePer'};
            if (is_string($data->{'ratePer'})) {
                $value_11 = $data->{'ratePer'};
            } elseif (is_null($data->{'ratePer'})) {
                $value_11 = $data->{'ratePer'};
            }
            $object->setRatePer($value_11);
        }
        if (property_exists($data, 'salary')) {
            $value_12 = $data->{'salary'};
            if (is_float($data->{'salary'})) {
                $value_12 = $data->{'salary'};
            } elseif (is_null($data->{'salary'})) {
                $value_12 = $data->{'salary'};
            }
            $object->setSalary($value_12);
        }

        return $object;
    }

    public function normalize($object, $format = null, array $context = [])
    {
        $data = new \stdClass();
        $value = $object->getAnnualSalary();
        if (is_float($object->getAnnualSalary())) {
            $value = $object->getAnnualSalary();
        } elseif (is_null($object->getAnnualSalary())) {
            $value = $object->getAnnualSalary();
        }
        $data->{'annualSalary'} = $value;
        $value_1 = $object->getBaseRate();
        if (is_float($object->getBaseRate())) {
            $value_1 = $object->getBaseRate();
        } elseif (is_null($object->getBaseRate())) {
            $value_1 = $object->getBaseRate();
        }
        $data->{'baseRate'} = $value_1;
        $value_2 = $object->getBeginCheckDate();
        if (is_string($object->getBeginCheckDate())) {
            $value_2 = $object->getBeginCheckDate();
        } elseif (is_null($object->getBeginCheckDate())) {
            $value_2 = $object->getBeginCheckDate();
        }
        $data->{'beginCheckDate'} = $value_2;
        $value_3 = $object->getChangeReason();
        if (is_string($object->getChangeReason())) {
            $value_3 = $object->getChangeReason();
        } elseif (is_null($object->getChangeReason())) {
            $value_3 = $object->getChangeReason();
        }
        $data->{'changeReason'} = $value_3;
        $value_4 = $object->getDefaultHours();
        if (is_float($object->getDefaultHours())) {
            $value_4 = $object->getDefaultHours();
        } elseif (is_null($object->getDefaultHours())) {
            $value_4 = $object->getDefaultHours();
        }
        $data->{'defaultHours'} = $value_4;
        $value_5 = $object->getEffectiveDate();
        if (is_string($object->getEffectiveDate())) {
            $value_5 = $object->getEffectiveDate();
        } elseif (is_null($object->getEffectiveDate())) {
            $value_5 = $object->getEffectiveDate();
        }
        $data->{'effectiveDate'} = $value_5;
        $value_6 = $object->getIsAutoPay();
        if (is_bool($object->getIsAutoPay())) {
            $value_6 = $object->getIsAutoPay();
        } elseif (is_null($object->getIsAutoPay())) {
            $value_6 = $object->getIsAutoPay();
        }
        $data->{'isAutoPay'} = $value_6;
        $value_7 = $object->getPayFrequency();
        if (is_string($object->getPayFrequency())) {
            $value_7 = $object->getPayFrequency();
        } elseif (is_null($object->getPayFrequency())) {
            $value_7 = $object->getPayFrequency();
        }
        $data->{'payFrequency'} = $value_7;
        $value_8 = $object->getPayGrade();
        if (is_string($object->getPayGrade())) {
            $value_8 = $object->getPayGrade();
        } elseif (is_null($object->getPayGrade())) {
            $value_8 = $object->getPayGrade();
        }
        $data->{'payGrade'} = $value_8;
        $value_9 = $object->getPayRateNote();
        if (is_string($object->getPayRateNote())) {
            $value_9 = $object->getPayRateNote();
        } elseif (is_null($object->getPayRateNote())) {
            $value_9 = $object->getPayRateNote();
        }
        $data->{'payRateNote'} = $value_9;
        $value_10 = $object->getPayType();
        if (is_string($object->getPayType())) {
            $value_10 = $object->getPayType();
        } elseif (is_null($object->getPayType())) {
            $value_10 = $object->getPayType();
        }
        $data->{'payType'} = $value_10;
        $value_11 = $object->getRatePer();
        if (is_string($object->getRatePer())) {
            $value_11 = $object->getRatePer();
        } elseif (is_null($object->getRatePer())) {
            $value_11 = $object->getRatePer();
        }
        $data->{'ratePer'} = $value_11;
        $value_12 = $object->getSalary();
        if (is_float($object->getSalary())) {
            $value_12 = $object->getSalary();
        } elseif (is_null($object->getSalary())) {
            $value_12 = $object->getSalary();
        }
        $data->{'salary'} = $value_12;

        return $data;
    }
}
