<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Paylocity\Api\Model;

class BenefitSetup
{
    /**
     * Benefit Class code. Values are configured in Web Pay Company > Setup > Benefits > Classes.<br  />Max length: 30.
     *
     * @var string|null
     */
    protected $benefitClass;
    /**
     * Date when Benefit Class takes effect. Common formats include *MM-DD-CCYY*, *CCYY-MM-DD*.
     *
     * @var string|null
     */
    protected $benefitClassEffectiveDate;
    /**
     * Salary used to configure benefits.<br  />Decimal(12,2).
     *
     * @var float|null
     */
    protected $benefitSalary;
    /**
     * Date when Benefit Salary takes effect. Common formats include *MM-DD-CCYY*, *CCYY-MM-DD*.
     *
     * @var string|null
     */
    protected $benefitSalaryEffectiveDate;
    /**
     * Applicable only for HR Enhanced clients and Benefit Classes with ACA Employment Type of Full Time.
     *
     * @var bool|null
     */
    protected $doNotApplyAdministrativePeriod;
    /**
     * Only valid for HR Enhanced clients and Benefit Classes that are ACA Employment Type of Full Time.
     *
     * @var bool|null
     */
    protected $isMeasureAcaEligibility;

    /**
     * Benefit Class code. Values are configured in Web Pay Company > Setup > Benefits > Classes.<br  />Max length: 30.
     */
    public function getBenefitClass(): ?string
    {
        return $this->benefitClass;
    }

    /**
     * Benefit Class code. Values are configured in Web Pay Company > Setup > Benefits > Classes.<br  />Max length: 30.
     */
    public function setBenefitClass(?string $benefitClass): self
    {
        $this->benefitClass = $benefitClass;

        return $this;
    }

    /**
     * Date when Benefit Class takes effect. Common formats include *MM-DD-CCYY*, *CCYY-MM-DD*.
     */
    public function getBenefitClassEffectiveDate(): ?string
    {
        return $this->benefitClassEffectiveDate;
    }

    /**
     * Date when Benefit Class takes effect. Common formats include *MM-DD-CCYY*, *CCYY-MM-DD*.
     */
    public function setBenefitClassEffectiveDate(?string $benefitClassEffectiveDate): self
    {
        $this->benefitClassEffectiveDate = $benefitClassEffectiveDate;

        return $this;
    }

    /**
     * Salary used to configure benefits.<br  />Decimal(12,2).
     */
    public function getBenefitSalary(): ?float
    {
        return $this->benefitSalary;
    }

    /**
     * Salary used to configure benefits.<br  />Decimal(12,2).
     */
    public function setBenefitSalary(?float $benefitSalary): self
    {
        $this->benefitSalary = $benefitSalary;

        return $this;
    }

    /**
     * Date when Benefit Salary takes effect. Common formats include *MM-DD-CCYY*, *CCYY-MM-DD*.
     */
    public function getBenefitSalaryEffectiveDate(): ?string
    {
        return $this->benefitSalaryEffectiveDate;
    }

    /**
     * Date when Benefit Salary takes effect. Common formats include *MM-DD-CCYY*, *CCYY-MM-DD*.
     */
    public function setBenefitSalaryEffectiveDate(?string $benefitSalaryEffectiveDate): self
    {
        $this->benefitSalaryEffectiveDate = $benefitSalaryEffectiveDate;

        return $this;
    }

    /**
     * Applicable only for HR Enhanced clients and Benefit Classes with ACA Employment Type of Full Time.
     */
    public function getDoNotApplyAdministrativePeriod(): ?bool
    {
        return $this->doNotApplyAdministrativePeriod;
    }

    /**
     * Applicable only for HR Enhanced clients and Benefit Classes with ACA Employment Type of Full Time.
     */
    public function setDoNotApplyAdministrativePeriod(?bool $doNotApplyAdministrativePeriod): self
    {
        $this->doNotApplyAdministrativePeriod = $doNotApplyAdministrativePeriod;

        return $this;
    }

    /**
     * Only valid for HR Enhanced clients and Benefit Classes that are ACA Employment Type of Full Time.
     */
    public function getIsMeasureAcaEligibility(): ?bool
    {
        return $this->isMeasureAcaEligibility;
    }

    /**
     * Only valid for HR Enhanced clients and Benefit Classes that are ACA Employment Type of Full Time.
     */
    public function setIsMeasureAcaEligibility(?bool $isMeasureAcaEligibility): self
    {
        $this->isMeasureAcaEligibility = $isMeasureAcaEligibility;

        return $this;
    }
}
