<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Paylocity\Api\Model;

class CompanyCodes
{
    /**
     * Code.<br  /> Max length: 40.
     *
     * @var string|null
     */
    protected $code;
    /**
     * Description. <br  /> Max length: 150.
     *
     * @var string|null
     */
    protected $description;

    /**
     * Code.<br  /> Max length: 40.
     */
    public function getCode(): ?string
    {
        return $this->code;
    }

    /**
     * Code.<br  /> Max length: 40.
     */
    public function setCode(?string $code): self
    {
        $this->code = $code;

        return $this;
    }

    /**
     * Description. <br  /> Max length: 150.
     */
    public function getDescription(): ?string
    {
        return $this->description;
    }

    /**
     * Description. <br  /> Max length: 150.
     */
    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }
}
