<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Paylocity\Api\Model;

class EmergencyContact
{
    /**
     * 1st address line.
     *
     * @var string
     */
    protected $address1;
    /**
     * Valid values are *true* or *false*.
     *
     * @var bool
     */
    protected $syncEmployeeInfo;

    /**
     * 1st address line.
     */
    public function getAddress1(): string
    {
        return $this->address1;
    }

    /**
     * 1st address line.
     */
    public function setAddress1(string $address1): self
    {
        $this->address1 = $address1;

        return $this;
    }

    /**
     * Valid values are *true* or *false*.
     */
    public function getSyncEmployeeInfo(): bool
    {
        return $this->syncEmployeeInfo;
    }

    /**
     * Valid values are *true* or *false*.
     */
    public function setSyncEmployeeInfo(bool $syncEmployeeInfo): self
    {
        $this->syncEmployeeInfo = $syncEmployeeInfo;

        return $this;
    }
}
