<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Paylocity\Api\Model;

class EmployeeWorkAddress
{
    /**
     * 1st address line.<br  /> Max length: 40.
     *
     * @var string|null
     */
    protected $address1;
    /**
     * 2nd address line. <br  /> Max length: 40.
     *
     * @var string|null
     */
    protected $address2;
    /**
     * City.<br  /> Max length: 40.
     *
     * @var string|null
     */
    protected $city;
    /**
     * Country.<br  /> Max length: 30.
     *
     * @var string|null
     */
    protected $country;
    /**
     * County.<br  /> Max length: 30.
     *
     * @var string|null
     */
    protected $county;
    /**
     * Email. <br  />Max length: 50.
     *
     * @var string|null
     */
    protected $emailAddress;
    /**
     * Work Location name. <br />Max length: 50.
     *
     * @var string|null
     */
    protected $location;
    /**
     * Employee mail stop.<br  /> Max length: 10.
     *
     * @var string|null
     */
    protected $mailStop;
    /**
     * Mobile phone number.<br  /> Max length: 12.
     *
     * @var string|null
     */
    protected $mobilePhone;
    /**
     * Employee pager number.<br  /> Max length: 20.
     *
     * @var string|null
     */
    protected $pager;
    /**
     * Phone number.<br  /> Max length: 12.
     *
     * @var string|null
     */
    protected $phone;
    /**
     * Phone number extension.<br  /> Max length: 10.
     *
     * @var string|null
     */
    protected $phoneExtension;
    /**
     * Postal code.<br  /> Max length: 10.
     *
     * @var string|null
     */
    protected $postalCode;
    /**
     * State or province.<br  /> Max length: 2.
     *
     * @var string|null
     */
    protected $state;

    /**
     * 1st address line.<br  /> Max length: 40.
     */
    public function getAddress1(): ?string
    {
        return $this->address1;
    }

    /**
     * 1st address line.<br  /> Max length: 40.
     */
    public function setAddress1(?string $address1): self
    {
        $this->address1 = $address1;

        return $this;
    }

    /**
     * 2nd address line. <br  /> Max length: 40.
     */
    public function getAddress2(): ?string
    {
        return $this->address2;
    }

    /**
     * 2nd address line. <br  /> Max length: 40.
     */
    public function setAddress2(?string $address2): self
    {
        $this->address2 = $address2;

        return $this;
    }

    /**
     * City.<br  /> Max length: 40.
     */
    public function getCity(): ?string
    {
        return $this->city;
    }

    /**
     * City.<br  /> Max length: 40.
     */
    public function setCity(?string $city): self
    {
        $this->city = $city;

        return $this;
    }

    /**
     * Country.<br  /> Max length: 30.
     */
    public function getCountry(): ?string
    {
        return $this->country;
    }

    /**
     * Country.<br  /> Max length: 30.
     */
    public function setCountry(?string $country): self
    {
        $this->country = $country;

        return $this;
    }

    /**
     * County.<br  /> Max length: 30.
     */
    public function getCounty(): ?string
    {
        return $this->county;
    }

    /**
     * County.<br  /> Max length: 30.
     */
    public function setCounty(?string $county): self
    {
        $this->county = $county;

        return $this;
    }

    /**
     * Email. <br  />Max length: 50.
     */
    public function getEmailAddress(): ?string
    {
        return $this->emailAddress;
    }

    /**
     * Email. <br  />Max length: 50.
     */
    public function setEmailAddress(?string $emailAddress): self
    {
        $this->emailAddress = $emailAddress;

        return $this;
    }

    /**
     * Work Location name. <br />Max length: 50.
     */
    public function getLocation(): ?string
    {
        return $this->location;
    }

    /**
     * Work Location name. <br />Max length: 50.
     */
    public function setLocation(?string $location): self
    {
        $this->location = $location;

        return $this;
    }

    /**
     * Employee mail stop.<br  /> Max length: 10.
     */
    public function getMailStop(): ?string
    {
        return $this->mailStop;
    }

    /**
     * Employee mail stop.<br  /> Max length: 10.
     */
    public function setMailStop(?string $mailStop): self
    {
        $this->mailStop = $mailStop;

        return $this;
    }

    /**
     * Mobile phone number.<br  /> Max length: 12.
     */
    public function getMobilePhone(): ?string
    {
        return $this->mobilePhone;
    }

    /**
     * Mobile phone number.<br  /> Max length: 12.
     */
    public function setMobilePhone(?string $mobilePhone): self
    {
        $this->mobilePhone = $mobilePhone;

        return $this;
    }

    /**
     * Employee pager number.<br  /> Max length: 20.
     */
    public function getPager(): ?string
    {
        return $this->pager;
    }

    /**
     * Employee pager number.<br  /> Max length: 20.
     */
    public function setPager(?string $pager): self
    {
        $this->pager = $pager;

        return $this;
    }

    /**
     * Phone number.<br  /> Max length: 12.
     */
    public function getPhone(): ?string
    {
        return $this->phone;
    }

    /**
     * Phone number.<br  /> Max length: 12.
     */
    public function setPhone(?string $phone): self
    {
        $this->phone = $phone;

        return $this;
    }

    /**
     * Phone number extension.<br  /> Max length: 10.
     */
    public function getPhoneExtension(): ?string
    {
        return $this->phoneExtension;
    }

    /**
     * Phone number extension.<br  /> Max length: 10.
     */
    public function setPhoneExtension(?string $phoneExtension): self
    {
        $this->phoneExtension = $phoneExtension;

        return $this;
    }

    /**
     * Postal code.<br  /> Max length: 10.
     */
    public function getPostalCode(): ?string
    {
        return $this->postalCode;
    }

    /**
     * Postal code.<br  /> Max length: 10.
     */
    public function setPostalCode(?string $postalCode): self
    {
        $this->postalCode = $postalCode;

        return $this;
    }

    /**
     * State or province.<br  /> Max length: 2.
     */
    public function getState(): ?string
    {
        return $this->state;
    }

    /**
     * State or province.<br  /> Max length: 2.
     */
    public function setState(?string $state): self
    {
        $this->state = $state;

        return $this;
    }
}
