<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Paylocity\Api\Model;

class EmployeeAdditionalDirectDepositItem
{
    /**
     * Account number, entered without special characters and spaces. <br  />Max length: 17<br />.
     *
     * @var string|null
     */
    protected $accountNumber;
    /**
     * Account type. Valid values are *C* (Checking), *S* (Saving), *P* (Pay Card). <br   />Max length: 1<br />.
     *
     * @var string|null
     */
    protected $accountType;
    /**
     * Amount value to be deposited to the account.<br  />Decimal (12,2)<br />.
     *
     * @var float|null
     */
    protected $amount;
    /**
     * Amount type to indicate the context of the amount. Common values are *F* (FLAT), *F-* (Net Minus), *P* (Percent). <br  /> Max length: 5<br />.
     *
     * @var string|null
     */
    protected $amountType;
    /**
     * Indicates if direct deposit should be blocked when special check types such as Bonus are processed.<br />.
     *
     * @var bool|null
     */
    protected $blockSpecial;
    /**
     * Indicates if account will not pre-note.<br />.
     *
     * @var bool|null
     */
    protected $isSkipPreNote;
    /**
     * Name on the bank account. Defaults to employee's name. <br  />Max length: 30<br />.
     *
     * @var string|null
     */
    protected $nameOnAccount;
    /**
     * Date to end the pre-note of the account. Common formats include *MM-DD-CCYY*, *CCYY-MM-DD*.<br />.
     *
     * @var string|null
     */
    protected $preNoteDate;
    /**
     * ABA Transit Routing Number, entered without dashes or spaces. <br  />Max length: 9<br />.
     *
     * @var string|null
     */
    protected $routingNumber;

    /**
     * Account number, entered without special characters and spaces. <br  />Max length: 17<br />.
     */
    public function getAccountNumber(): ?string
    {
        return $this->accountNumber;
    }

    /**
     * Account number, entered without special characters and spaces. <br  />Max length: 17<br />.
     */
    public function setAccountNumber(?string $accountNumber): self
    {
        $this->accountNumber = $accountNumber;

        return $this;
    }

    /**
     * Account type. Valid values are *C* (Checking), *S* (Saving), *P* (Pay Card). <br   />Max length: 1<br />.
     */
    public function getAccountType(): ?string
    {
        return $this->accountType;
    }

    /**
     * Account type. Valid values are *C* (Checking), *S* (Saving), *P* (Pay Card). <br   />Max length: 1<br />.
     */
    public function setAccountType(?string $accountType): self
    {
        $this->accountType = $accountType;

        return $this;
    }

    /**
     * Amount value to be deposited to the account.<br  />Decimal (12,2)<br />.
     */
    public function getAmount(): ?float
    {
        return $this->amount;
    }

    /**
     * Amount value to be deposited to the account.<br  />Decimal (12,2)<br />.
     */
    public function setAmount(?float $amount): self
    {
        $this->amount = $amount;

        return $this;
    }

    /**
     * Amount type to indicate the context of the amount. Common values are *F* (FLAT), *F-* (Net Minus), *P* (Percent). <br  /> Max length: 5<br />.
     */
    public function getAmountType(): ?string
    {
        return $this->amountType;
    }

    /**
     * Amount type to indicate the context of the amount. Common values are *F* (FLAT), *F-* (Net Minus), *P* (Percent). <br  /> Max length: 5<br />.
     */
    public function setAmountType(?string $amountType): self
    {
        $this->amountType = $amountType;

        return $this;
    }

    /**
     * Indicates if direct deposit should be blocked when special check types such as Bonus are processed.<br />.
     */
    public function getBlockSpecial(): ?bool
    {
        return $this->blockSpecial;
    }

    /**
     * Indicates if direct deposit should be blocked when special check types such as Bonus are processed.<br />.
     */
    public function setBlockSpecial(?bool $blockSpecial): self
    {
        $this->blockSpecial = $blockSpecial;

        return $this;
    }

    /**
     * Indicates if account will not pre-note.<br />.
     */
    public function getIsSkipPreNote(): ?bool
    {
        return $this->isSkipPreNote;
    }

    /**
     * Indicates if account will not pre-note.<br />.
     */
    public function setIsSkipPreNote(?bool $isSkipPreNote): self
    {
        $this->isSkipPreNote = $isSkipPreNote;

        return $this;
    }

    /**
     * Name on the bank account. Defaults to employee's name. <br  />Max length: 30<br />.
     */
    public function getNameOnAccount(): ?string
    {
        return $this->nameOnAccount;
    }

    /**
     * Name on the bank account. Defaults to employee's name. <br  />Max length: 30<br />.
     */
    public function setNameOnAccount(?string $nameOnAccount): self
    {
        $this->nameOnAccount = $nameOnAccount;

        return $this;
    }

    /**
     * Date to end the pre-note of the account. Common formats include *MM-DD-CCYY*, *CCYY-MM-DD*.<br />.
     */
    public function getPreNoteDate(): ?string
    {
        return $this->preNoteDate;
    }

    /**
     * Date to end the pre-note of the account. Common formats include *MM-DD-CCYY*, *CCYY-MM-DD*.<br />.
     */
    public function setPreNoteDate(?string $preNoteDate): self
    {
        $this->preNoteDate = $preNoteDate;

        return $this;
    }

    /**
     * ABA Transit Routing Number, entered without dashes or spaces. <br  />Max length: 9<br />.
     */
    public function getRoutingNumber(): ?string
    {
        return $this->routingNumber;
    }

    /**
     * ABA Transit Routing Number, entered without dashes or spaces. <br  />Max length: 9<br />.
     */
    public function setRoutingNumber(?string $routingNumber): self
    {
        $this->routingNumber = $routingNumber;

        return $this;
    }
}
