<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Paylocity\Api\Model;

class Employee
{
    /**
     * Add up to 19 direct deposit accounts in addition to the main direct deposit account. IMPORTANT: A direct deposit update will remove ALL existing main and additional direct deposit information in WebPay and replace with information provided on the request. GET API will not return direct deposit data.
     *
     * @var EmployeeAdditionalDirectDepositItem[]
     */
    protected $additionalDirectDeposit;
    /**
     * Add Additional Rates.
     *
     * @var EmployeeAdditionalRateItem[]
     */
    protected $additionalRate;
    /**
     *  Add or update setup values used for employee benefits integration, insurance plan settings, and ACA reporting.
     *
     * @var EmployeeBenefitSetup
     */
    protected $benefitSetup;
    /**
     * Employee birthdate. Common formats include *MM-DD-CCYY*, *CCYY-MM-DD*.
     *
     * @var string|null
     */
    protected $birthDate;
    /**
     * Company name as defined in Web Pay, applicable with GET requests only.<br  /> Max length: 50.
     *
     * @var string|null
     */
    protected $companyName;
    /**
     * Employee is paid in this currency. <br  />Max length: 30.
     *
     * @var string|null
     */
    protected $currency;
    /**
     * Up to 8 custom fields of boolean (checkbox) type value.
     *
     * @var EmployeeCustomBooleanFieldsItem[]
     */
    protected $customBooleanFields;
    /**
     * Up to 8 custom fields of the date type value.
     *
     * @var EmployeeCustomDateFieldsItem[]
     */
    protected $customDateFields;
    /**
     * Up to 8 custom fields of the dropdown type value.
     *
     * @var EmployeeCustomDropDownFieldsItem[]
     */
    protected $customDropDownFields;
    /**
     * Up to 8 custom fields of numeric type value.
     *
     * @var EmployeeCustomNumberFieldsItem[]
     */
    protected $customNumberFields;
    /**
     * Up to 8 custom fields of text type value.
     *
     * @var EmployeeCustomTextFieldsItem[]
     */
    protected $customTextFields;
    /**
     * Add or update home department cost center, position, supervisor, reviewer, employment type, EEO class, pay settings, and union information.
     *
     * @var EmployeeDepartmentPosition
     */
    protected $departmentPosition;
    /**
     * Indicates if employee has disability status.
     *
     * @var string|null
     */
    protected $disabilityDescription;
    /**
     * Add or update Emergency Contacts.
     *
     * @var EmployeeEmergencyContactsItem[]
     */
    protected $emergencyContacts;
    /**
     * Leave blank to have Web Pay automatically assign the next available employee ID.<br  />Max length: 10.
     *
     * @var string|null
     */
    protected $employeeId;
    /**
     * Employee ethnicity.<br  /> Max length: 10.
     *
     * @var string|null
     */
    protected $ethnicity;
    /**
     * Add or update federal tax amount type (taxCalculationCode), amount or percentage, filing status, and exemptions.
     *
     * @var EmployeeFederalTax
     */
    protected $federalTax;
    /**
     * Employee first name. <br  />Max length: 40.
     *
     * @var string|null
     */
    protected $firstName;
    /**
     * Employee gender. Common values *M* (Male), *F* (Female). <br  />Max length: 1.
     *
     * @var string|null
     */
    protected $gender;
    /**
     * Add or update employee's home address, personal phone numbers, and personal email.
     *
     * @var EmployeeHomeAddress
     */
    protected $homeAddress;
    /**
     * Indicates if employee meets the highly compensated employee criteria.
     *
     * @var bool
     */
    protected $isHighlyCompensated;
    /**
     * Indicates if employee is a smoker.
     *
     * @var bool
     */
    protected $isSmoker;
    /**
     * Employee last name. <br  />Max length: 40.
     *
     * @var string|null
     */
    protected $lastName;
    /**
     * Add, update, or delete local tax code, filing status, and exemptions including  PA-PSD taxes.
     *
     * @var EmployeeLocalTaxItem[]
     */
    protected $localTax;
    /**
     * Add the main direct deposit account. After deposits are made to any additional direct deposit accounts, the remaining net check is deposited in the main direct deposit account. IMPORTANT: A direct deposit update will remove ALL existing main and additional direct deposit information in WebPay and replace with what is provided on the request. GET API will not return direct deposit data.
     *
     * @var EmployeeMainDirectDeposit
     */
    protected $mainDirectDeposit;
    /**
     * Employee marital status. Common values *D (Divorced), M (Married), S (Single), W (Widowed)*. <br  />Max length: 10.
     *
     * @var string|null
     */
    protected $maritalStatus;
    /**
     * Employee middle name.<br  /> Max length: 20.
     *
     * @var string|null
     */
    protected $middleName;
    /**
     * Add or update non-primary state tax code, amount type (taxCalculationCode), amount or percentage, filing status, exemptions, supplemental check (specialCheckCalc), and reciprocity code information.
     *
     * @var EmployeeNonPrimaryStateTax
     */
    protected $nonPrimaryStateTax;
    /**
     * Percentage of employee's ownership in the company, entered as a whole number. <br  /> Decimal (12,2).
     *
     * @var float|null
     */
    protected $ownerPercent;
    /**
     * Employee preferred display name.<br  /> Max length: 20.
     *
     * @var string|null
     */
    protected $preferredName;
    /**
     * Add or update hourly or salary pay rate, effective date, and pay frequency.
     *
     * @var EmployeePrimaryPayRate
     */
    protected $primaryPayRate;
    /**
     * Add or update primary state tax code, amount type (taxCalculationCode), amount or percentage, filing status, exemptions, and supplemental check (specialCheckCalc) information. Only one primary state is allowed. Sending an updated primary state will replace the current primary state.
     *
     * @var EmployeePrimaryStateTax
     */
    protected $primaryStateTax;
    /**
     * Prior last name if applicable.<br  />Max length: 40.
     *
     * @var string|null
     */
    protected $priorLastName;
    /**
     * Employee preferred salutation. <br  />Max length: 10.
     *
     * @var string|null
     */
    protected $salutation;
    /**
     * Employee social security number. Leave it blank if valid social security number not available. <br  />Max length: 11.
     *
     * @var string|null
     */
    protected $ssn;
    /**
     * Add or update employee status, change reason, effective date, and adjusted seniority date. Note that companies that are still in Implementation cannot hire future employees.
     *
     * @var EmployeeStatus
     */
    protected $status;
    /**
     * Employee name suffix. Common values are *Jr, Sr, II*.<br  />Max length: 30.
     *
     * @var string|null
     */
    protected $suffix;
    /**
     * Add tax form, 1099 exempt reasons and notes, and 943 agricultural employee information. Once the employee receives wages, this information cannot be updated. Add or update SUI tax state, retirement plan, and statutory information.
     *
     * @var EmployeeTaxSetup
     */
    protected $taxSetup;
    /**
     * Indicates if employee is a veteran.
     *
     * @var string|null
     */
    protected $veteranDescription;
    /**
     * Add or update Web Time badge number and charge rate and synchronize Web Pay and Web Time employee data.
     *
     * @var EmployeeWebTime
     */
    protected $webTime;
    /**
     * Add or update employee's work address, phone numbers, and email. Work Location drop down field is not included.
     *
     * @var EmployeeWorkAddress
     */
    protected $workAddress;
    /**
     * Add or update I-9 work authorization information.
     *
     * @var EmployeeWorkEligibility
     */
    protected $workEligibility;

    /**
     * Add up to 19 direct deposit accounts in addition to the main direct deposit account. IMPORTANT: A direct deposit update will remove ALL existing main and additional direct deposit information in WebPay and replace with information provided on the request. GET API will not return direct deposit data.
     *
     * @return EmployeeAdditionalDirectDepositItem[]
     */
    public function getAdditionalDirectDeposit(): array
    {
        return $this->additionalDirectDeposit;
    }

    /**
     * Add up to 19 direct deposit accounts in addition to the main direct deposit account. IMPORTANT: A direct deposit update will remove ALL existing main and additional direct deposit information in WebPay and replace with information provided on the request. GET API will not return direct deposit data.
     *
     * @param EmployeeAdditionalDirectDepositItem[] $additionalDirectDeposit
     */
    public function setAdditionalDirectDeposit(array $additionalDirectDeposit): self
    {
        $this->additionalDirectDeposit = $additionalDirectDeposit;

        return $this;
    }

    /**
     * Add Additional Rates.
     *
     * @return EmployeeAdditionalRateItem[]
     */
    public function getAdditionalRate(): array
    {
        return $this->additionalRate;
    }

    /**
     * Add Additional Rates.
     *
     * @param EmployeeAdditionalRateItem[] $additionalRate
     */
    public function setAdditionalRate(array $additionalRate): self
    {
        $this->additionalRate = $additionalRate;

        return $this;
    }

    /**
     *  Add or update setup values used for employee benefits integration, insurance plan settings, and ACA reporting.
     */
    public function getBenefitSetup(): EmployeeBenefitSetup
    {
        return $this->benefitSetup;
    }

    /**
     *  Add or update setup values used for employee benefits integration, insurance plan settings, and ACA reporting.
     */
    public function setBenefitSetup(EmployeeBenefitSetup $benefitSetup): self
    {
        $this->benefitSetup = $benefitSetup;

        return $this;
    }

    /**
     * Employee birthdate. Common formats include *MM-DD-CCYY*, *CCYY-MM-DD*.
     */
    public function getBirthDate(): ?string
    {
        return $this->birthDate;
    }

    /**
     * Employee birthdate. Common formats include *MM-DD-CCYY*, *CCYY-MM-DD*.
     */
    public function setBirthDate(?string $birthDate): self
    {
        $this->birthDate = $birthDate;

        return $this;
    }

    /**
     * Company name as defined in Web Pay, applicable with GET requests only.<br  /> Max length: 50.
     */
    public function getCompanyName(): ?string
    {
        return $this->companyName;
    }

    /**
     * Company name as defined in Web Pay, applicable with GET requests only.<br  /> Max length: 50.
     */
    public function setCompanyName(?string $companyName): self
    {
        $this->companyName = $companyName;

        return $this;
    }

    /**
     * Employee is paid in this currency. <br  />Max length: 30.
     */
    public function getCurrency(): ?string
    {
        return $this->currency;
    }

    /**
     * Employee is paid in this currency. <br  />Max length: 30.
     */
    public function setCurrency(?string $currency): self
    {
        $this->currency = $currency;

        return $this;
    }

    /**
     * Up to 8 custom fields of boolean (checkbox) type value.
     *
     * @return EmployeeCustomBooleanFieldsItem[]
     */
    public function getCustomBooleanFields(): array
    {
        return $this->customBooleanFields;
    }

    /**
     * Up to 8 custom fields of boolean (checkbox) type value.
     *
     * @param EmployeeCustomBooleanFieldsItem[] $customBooleanFields
     */
    public function setCustomBooleanFields(array $customBooleanFields): self
    {
        $this->customBooleanFields = $customBooleanFields;

        return $this;
    }

    /**
     * Up to 8 custom fields of the date type value.
     *
     * @return EmployeeCustomDateFieldsItem[]
     */
    public function getCustomDateFields(): array
    {
        return $this->customDateFields;
    }

    /**
     * Up to 8 custom fields of the date type value.
     *
     * @param EmployeeCustomDateFieldsItem[] $customDateFields
     */
    public function setCustomDateFields(array $customDateFields): self
    {
        $this->customDateFields = $customDateFields;

        return $this;
    }

    /**
     * Up to 8 custom fields of the dropdown type value.
     *
     * @return EmployeeCustomDropDownFieldsItem[]
     */
    public function getCustomDropDownFields(): array
    {
        return $this->customDropDownFields;
    }

    /**
     * Up to 8 custom fields of the dropdown type value.
     *
     * @param EmployeeCustomDropDownFieldsItem[] $customDropDownFields
     */
    public function setCustomDropDownFields(array $customDropDownFields): self
    {
        $this->customDropDownFields = $customDropDownFields;

        return $this;
    }

    /**
     * Up to 8 custom fields of numeric type value.
     *
     * @return EmployeeCustomNumberFieldsItem[]
     */
    public function getCustomNumberFields(): array
    {
        return $this->customNumberFields;
    }

    /**
     * Up to 8 custom fields of numeric type value.
     *
     * @param EmployeeCustomNumberFieldsItem[] $customNumberFields
     */
    public function setCustomNumberFields(array $customNumberFields): self
    {
        $this->customNumberFields = $customNumberFields;

        return $this;
    }

    /**
     * Up to 8 custom fields of text type value.
     *
     * @return EmployeeCustomTextFieldsItem[]
     */
    public function getCustomTextFields(): array
    {
        return $this->customTextFields;
    }

    /**
     * Up to 8 custom fields of text type value.
     *
     * @param EmployeeCustomTextFieldsItem[] $customTextFields
     */
    public function setCustomTextFields(array $customTextFields): self
    {
        $this->customTextFields = $customTextFields;

        return $this;
    }

    /**
     * Add or update home department cost center, position, supervisor, reviewer, employment type, EEO class, pay settings, and union information.
     */
    public function getDepartmentPosition(): EmployeeDepartmentPosition
    {
        return $this->departmentPosition;
    }

    /**
     * Add or update home department cost center, position, supervisor, reviewer, employment type, EEO class, pay settings, and union information.
     */
    public function setDepartmentPosition(EmployeeDepartmentPosition $departmentPosition): self
    {
        $this->departmentPosition = $departmentPosition;

        return $this;
    }

    /**
     * Indicates if employee has disability status.
     */
    public function getDisabilityDescription(): ?string
    {
        return $this->disabilityDescription;
    }

    /**
     * Indicates if employee has disability status.
     */
    public function setDisabilityDescription(?string $disabilityDescription): self
    {
        $this->disabilityDescription = $disabilityDescription;

        return $this;
    }

    /**
     * Add or update Emergency Contacts.
     *
     * @return EmployeeEmergencyContactsItem[]
     */
    public function getEmergencyContacts(): array
    {
        return $this->emergencyContacts;
    }

    /**
     * Add or update Emergency Contacts.
     *
     * @param EmployeeEmergencyContactsItem[] $emergencyContacts
     */
    public function setEmergencyContacts(array $emergencyContacts): self
    {
        $this->emergencyContacts = $emergencyContacts;

        return $this;
    }

    /**
     * Leave blank to have Web Pay automatically assign the next available employee ID.<br  />Max length: 10.
     */
    public function getEmployeeId(): ?string
    {
        return $this->employeeId;
    }

    /**
     * Leave blank to have Web Pay automatically assign the next available employee ID.<br  />Max length: 10.
     */
    public function setEmployeeId(?string $employeeId): self
    {
        $this->employeeId = $employeeId;

        return $this;
    }

    /**
     * Employee ethnicity.<br  /> Max length: 10.
     */
    public function getEthnicity(): ?string
    {
        return $this->ethnicity;
    }

    /**
     * Employee ethnicity.<br  /> Max length: 10.
     */
    public function setEthnicity(?string $ethnicity): self
    {
        $this->ethnicity = $ethnicity;

        return $this;
    }

    /**
     * Add or update federal tax amount type (taxCalculationCode), amount or percentage, filing status, and exemptions.
     */
    public function getFederalTax(): EmployeeFederalTax
    {
        return $this->federalTax;
    }

    /**
     * Add or update federal tax amount type (taxCalculationCode), amount or percentage, filing status, and exemptions.
     */
    public function setFederalTax(EmployeeFederalTax $federalTax): self
    {
        $this->federalTax = $federalTax;

        return $this;
    }

    /**
     * Employee first name. <br  />Max length: 40.
     */
    public function getFirstName(): ?string
    {
        return $this->firstName;
    }

    /**
     * Employee first name. <br  />Max length: 40.
     */
    public function setFirstName(?string $firstName): self
    {
        $this->firstName = $firstName;

        return $this;
    }

    /**
     * Employee gender. Common values *M* (Male), *F* (Female). <br  />Max length: 1.
     */
    public function getGender(): ?string
    {
        return $this->gender;
    }

    /**
     * Employee gender. Common values *M* (Male), *F* (Female). <br  />Max length: 1.
     */
    public function setGender(?string $gender): self
    {
        $this->gender = $gender;

        return $this;
    }

    /**
     * Add or update employee's home address, personal phone numbers, and personal email.
     */
    public function getHomeAddress(): EmployeeHomeAddress
    {
        return $this->homeAddress;
    }

    /**
     * Add or update employee's home address, personal phone numbers, and personal email.
     */
    public function setHomeAddress(EmployeeHomeAddress $homeAddress): self
    {
        $this->homeAddress = $homeAddress;

        return $this;
    }

    /**
     * Indicates if employee meets the highly compensated employee criteria.
     */
    public function getIsHighlyCompensated(): bool
    {
        return $this->isHighlyCompensated;
    }

    /**
     * Indicates if employee meets the highly compensated employee criteria.
     */
    public function setIsHighlyCompensated(bool $isHighlyCompensated): self
    {
        $this->isHighlyCompensated = $isHighlyCompensated;

        return $this;
    }

    /**
     * Indicates if employee is a smoker.
     */
    public function getIsSmoker(): bool
    {
        return $this->isSmoker;
    }

    /**
     * Indicates if employee is a smoker.
     */
    public function setIsSmoker(bool $isSmoker): self
    {
        $this->isSmoker = $isSmoker;

        return $this;
    }

    /**
     * Employee last name. <br  />Max length: 40.
     */
    public function getLastName(): ?string
    {
        return $this->lastName;
    }

    /**
     * Employee last name. <br  />Max length: 40.
     */
    public function setLastName(?string $lastName): self
    {
        $this->lastName = $lastName;

        return $this;
    }

    /**
     * Add, update, or delete local tax code, filing status, and exemptions including  PA-PSD taxes.
     *
     * @return EmployeeLocalTaxItem[]
     */
    public function getLocalTax(): array
    {
        return $this->localTax;
    }

    /**
     * Add, update, or delete local tax code, filing status, and exemptions including  PA-PSD taxes.
     *
     * @param EmployeeLocalTaxItem[] $localTax
     */
    public function setLocalTax(array $localTax): self
    {
        $this->localTax = $localTax;

        return $this;
    }

    /**
     * Add the main direct deposit account. After deposits are made to any additional direct deposit accounts, the remaining net check is deposited in the main direct deposit account. IMPORTANT: A direct deposit update will remove ALL existing main and additional direct deposit information in WebPay and replace with what is provided on the request. GET API will not return direct deposit data.
     */
    public function getMainDirectDeposit(): EmployeeMainDirectDeposit
    {
        return $this->mainDirectDeposit;
    }

    /**
     * Add the main direct deposit account. After deposits are made to any additional direct deposit accounts, the remaining net check is deposited in the main direct deposit account. IMPORTANT: A direct deposit update will remove ALL existing main and additional direct deposit information in WebPay and replace with what is provided on the request. GET API will not return direct deposit data.
     */
    public function setMainDirectDeposit(EmployeeMainDirectDeposit $mainDirectDeposit): self
    {
        $this->mainDirectDeposit = $mainDirectDeposit;

        return $this;
    }

    /**
     * Employee marital status. Common values *D (Divorced), M (Married), S (Single), W (Widowed)*. <br  />Max length: 10.
     */
    public function getMaritalStatus(): ?string
    {
        return $this->maritalStatus;
    }

    /**
     * Employee marital status. Common values *D (Divorced), M (Married), S (Single), W (Widowed)*. <br  />Max length: 10.
     */
    public function setMaritalStatus(?string $maritalStatus): self
    {
        $this->maritalStatus = $maritalStatus;

        return $this;
    }

    /**
     * Employee middle name.<br  /> Max length: 20.
     */
    public function getMiddleName(): ?string
    {
        return $this->middleName;
    }

    /**
     * Employee middle name.<br  /> Max length: 20.
     */
    public function setMiddleName(?string $middleName): self
    {
        $this->middleName = $middleName;

        return $this;
    }

    /**
     * Add or update non-primary state tax code, amount type (taxCalculationCode), amount or percentage, filing status, exemptions, supplemental check (specialCheckCalc), and reciprocity code information.
     */
    public function getNonPrimaryStateTax(): EmployeeNonPrimaryStateTax
    {
        return $this->nonPrimaryStateTax;
    }

    /**
     * Add or update non-primary state tax code, amount type (taxCalculationCode), amount or percentage, filing status, exemptions, supplemental check (specialCheckCalc), and reciprocity code information.
     */
    public function setNonPrimaryStateTax(EmployeeNonPrimaryStateTax $nonPrimaryStateTax): self
    {
        $this->nonPrimaryStateTax = $nonPrimaryStateTax;

        return $this;
    }

    /**
     * Percentage of employee's ownership in the company, entered as a whole number. <br  /> Decimal (12,2).
     */
    public function getOwnerPercent(): ?float
    {
        return $this->ownerPercent;
    }

    /**
     * Percentage of employee's ownership in the company, entered as a whole number. <br  /> Decimal (12,2).
     */
    public function setOwnerPercent(?float $ownerPercent): self
    {
        $this->ownerPercent = $ownerPercent;

        return $this;
    }

    /**
     * Employee preferred display name.<br  /> Max length: 20.
     */
    public function getPreferredName(): ?string
    {
        return $this->preferredName;
    }

    /**
     * Employee preferred display name.<br  /> Max length: 20.
     */
    public function setPreferredName(?string $preferredName): self
    {
        $this->preferredName = $preferredName;

        return $this;
    }

    /**
     * Add or update hourly or salary pay rate, effective date, and pay frequency.
     */
    public function getPrimaryPayRate(): EmployeePrimaryPayRate
    {
        return $this->primaryPayRate;
    }

    /**
     * Add or update hourly or salary pay rate, effective date, and pay frequency.
     */
    public function setPrimaryPayRate(EmployeePrimaryPayRate $primaryPayRate): self
    {
        $this->primaryPayRate = $primaryPayRate;

        return $this;
    }

    /**
     * Add or update primary state tax code, amount type (taxCalculationCode), amount or percentage, filing status, exemptions, and supplemental check (specialCheckCalc) information. Only one primary state is allowed. Sending an updated primary state will replace the current primary state.
     */
    public function getPrimaryStateTax(): EmployeePrimaryStateTax
    {
        return $this->primaryStateTax;
    }

    /**
     * Add or update primary state tax code, amount type (taxCalculationCode), amount or percentage, filing status, exemptions, and supplemental check (specialCheckCalc) information. Only one primary state is allowed. Sending an updated primary state will replace the current primary state.
     */
    public function setPrimaryStateTax(EmployeePrimaryStateTax $primaryStateTax): self
    {
        $this->primaryStateTax = $primaryStateTax;

        return $this;
    }

    /**
     * Prior last name if applicable.<br  />Max length: 40.
     */
    public function getPriorLastName(): ?string
    {
        return $this->priorLastName;
    }

    /**
     * Prior last name if applicable.<br  />Max length: 40.
     */
    public function setPriorLastName(?string $priorLastName): self
    {
        $this->priorLastName = $priorLastName;

        return $this;
    }

    /**
     * Employee preferred salutation. <br  />Max length: 10.
     */
    public function getSalutation(): ?string
    {
        return $this->salutation;
    }

    /**
     * Employee preferred salutation. <br  />Max length: 10.
     */
    public function setSalutation(?string $salutation): self
    {
        $this->salutation = $salutation;

        return $this;
    }

    /**
     * Employee social security number. Leave it blank if valid social security number not available. <br  />Max length: 11.
     */
    public function getSsn(): ?string
    {
        return $this->ssn;
    }

    /**
     * Employee social security number. Leave it blank if valid social security number not available. <br  />Max length: 11.
     */
    public function setSsn(?string $ssn): self
    {
        $this->ssn = $ssn;

        return $this;
    }

    /**
     * Add or update employee status, change reason, effective date, and adjusted seniority date. Note that companies that are still in Implementation cannot hire future employees.
     */
    public function getStatus(): EmployeeStatus
    {
        return $this->status;
    }

    /**
     * Add or update employee status, change reason, effective date, and adjusted seniority date. Note that companies that are still in Implementation cannot hire future employees.
     */
    public function setStatus(EmployeeStatus $status): self
    {
        $this->status = $status;

        return $this;
    }

    /**
     * Employee name suffix. Common values are *Jr, Sr, II*.<br  />Max length: 30.
     */
    public function getSuffix(): ?string
    {
        return $this->suffix;
    }

    /**
     * Employee name suffix. Common values are *Jr, Sr, II*.<br  />Max length: 30.
     */
    public function setSuffix(?string $suffix): self
    {
        $this->suffix = $suffix;

        return $this;
    }

    /**
     * Add tax form, 1099 exempt reasons and notes, and 943 agricultural employee information. Once the employee receives wages, this information cannot be updated. Add or update SUI tax state, retirement plan, and statutory information.
     */
    public function getTaxSetup(): EmployeeTaxSetup
    {
        return $this->taxSetup;
    }

    /**
     * Add tax form, 1099 exempt reasons and notes, and 943 agricultural employee information. Once the employee receives wages, this information cannot be updated. Add or update SUI tax state, retirement plan, and statutory information.
     */
    public function setTaxSetup(EmployeeTaxSetup $taxSetup): self
    {
        $this->taxSetup = $taxSetup;

        return $this;
    }

    /**
     * Indicates if employee is a veteran.
     */
    public function getVeteranDescription(): ?string
    {
        return $this->veteranDescription;
    }

    /**
     * Indicates if employee is a veteran.
     */
    public function setVeteranDescription(?string $veteranDescription): self
    {
        $this->veteranDescription = $veteranDescription;

        return $this;
    }

    /**
     * Add or update Web Time badge number and charge rate and synchronize Web Pay and Web Time employee data.
     */
    public function getWebTime(): EmployeeWebTime
    {
        return $this->webTime;
    }

    /**
     * Add or update Web Time badge number and charge rate and synchronize Web Pay and Web Time employee data.
     */
    public function setWebTime(EmployeeWebTime $webTime): self
    {
        $this->webTime = $webTime;

        return $this;
    }

    /**
     * Add or update employee's work address, phone numbers, and email. Work Location drop down field is not included.
     */
    public function getWorkAddress(): EmployeeWorkAddress
    {
        return $this->workAddress;
    }

    /**
     * Add or update employee's work address, phone numbers, and email. Work Location drop down field is not included.
     */
    public function setWorkAddress(EmployeeWorkAddress $workAddress): self
    {
        $this->workAddress = $workAddress;

        return $this;
    }

    /**
     * Add or update I-9 work authorization information.
     */
    public function getWorkEligibility(): EmployeeWorkEligibility
    {
        return $this->workEligibility;
    }

    /**
     * Add or update I-9 work authorization information.
     */
    public function setWorkEligibility(EmployeeWorkEligibility $workEligibility): self
    {
        $this->workEligibility = $workEligibility;

        return $this;
    }
}
