<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Paylocity\Api\Model;

class Error
{
    /**
     * The name of the field, or property in the request message that contains an error.
     *
     * @var string
     */
    protected $field;
    /**
     * The error message.
     *
     * @var string
     */
    protected $message;
    /**
     * A list of options associated with this error. These options may indicate valid values for the field, or property that contains an error.
     *
     * @var ErrorOptionsItem[]
     */
    protected $options;
    /**
     * The JSON path of the field, or property, that contains an error in the request message.
     *
     * @var string
     */
    protected $path;

    /**
     * The name of the field, or property in the request message that contains an error.
     */
    public function getField(): string
    {
        return $this->field;
    }

    /**
     * The name of the field, or property in the request message that contains an error.
     */
    public function setField(string $field): self
    {
        $this->field = $field;

        return $this;
    }

    /**
     * The error message.
     */
    public function getMessage(): string
    {
        return $this->message;
    }

    /**
     * The error message.
     */
    public function setMessage(string $message): self
    {
        $this->message = $message;

        return $this;
    }

    /**
     * A list of options associated with this error. These options may indicate valid values for the field, or property that contains an error.
     *
     * @return ErrorOptionsItem[]
     */
    public function getOptions(): array
    {
        return $this->options;
    }

    /**
     * A list of options associated with this error. These options may indicate valid values for the field, or property that contains an error.
     *
     * @param ErrorOptionsItem[] $options
     */
    public function setOptions(array $options): self
    {
        $this->options = $options;

        return $this;
    }

    /**
     * The JSON path of the field, or property, that contains an error in the request message.
     */
    public function getPath(): string
    {
        return $this->path;
    }

    /**
     * The JSON path of the field, or property, that contains an error in the request message.
     */
    public function setPath(string $path): self
    {
        $this->path = $path;

        return $this;
    }
}
