<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Paylocity\Api\Model;

class StagedEmployeeMainDirectDepositItem
{
    /**
     * Account number, entered without special characters and spaces. <br  />Max length: 17.
     *
     * @var string|null
     */
    protected $accountNumber;
    /**
     * Account type. Valid values are *C* (Checking), *S* (Saving), *P* (Pay Card). <br   />Max length: 1.
     *
     * @var string|null
     */
    protected $accountType;
    /**
     * Indicates if account will not pre-note.
     *
     * @var bool|null
     */
    protected $isSkipPreNote;
    /**
     * Date to end the pre-note of the account. Common formats include *MM-DD-CCYY*, *CCYY-MM-DD*.
     *
     * @var string|null
     */
    protected $preNoteDate;
    /**
     * ABA Transit Routing Number, entered without dashes or spaces. <br  />Max length: 9.
     *
     * @var string|null
     */
    protected $routingNumber;

    /**
     * Account number, entered without special characters and spaces. <br  />Max length: 17.
     */
    public function getAccountNumber(): ?string
    {
        return $this->accountNumber;
    }

    /**
     * Account number, entered without special characters and spaces. <br  />Max length: 17.
     */
    public function setAccountNumber(?string $accountNumber): self
    {
        $this->accountNumber = $accountNumber;

        return $this;
    }

    /**
     * Account type. Valid values are *C* (Checking), *S* (Saving), *P* (Pay Card). <br   />Max length: 1.
     */
    public function getAccountType(): ?string
    {
        return $this->accountType;
    }

    /**
     * Account type. Valid values are *C* (Checking), *S* (Saving), *P* (Pay Card). <br   />Max length: 1.
     */
    public function setAccountType(?string $accountType): self
    {
        $this->accountType = $accountType;

        return $this;
    }

    /**
     * Indicates if account will not pre-note.
     */
    public function getIsSkipPreNote(): ?bool
    {
        return $this->isSkipPreNote;
    }

    /**
     * Indicates if account will not pre-note.
     */
    public function setIsSkipPreNote(?bool $isSkipPreNote): self
    {
        $this->isSkipPreNote = $isSkipPreNote;

        return $this;
    }

    /**
     * Date to end the pre-note of the account. Common formats include *MM-DD-CCYY*, *CCYY-MM-DD*.
     */
    public function getPreNoteDate(): ?string
    {
        return $this->preNoteDate;
    }

    /**
     * Date to end the pre-note of the account. Common formats include *MM-DD-CCYY*, *CCYY-MM-DD*.
     */
    public function setPreNoteDate(?string $preNoteDate): self
    {
        $this->preNoteDate = $preNoteDate;

        return $this;
    }

    /**
     * ABA Transit Routing Number, entered without dashes or spaces. <br  />Max length: 9.
     */
    public function getRoutingNumber(): ?string
    {
        return $this->routingNumber;
    }

    /**
     * ABA Transit Routing Number, entered without dashes or spaces. <br  />Max length: 9.
     */
    public function setRoutingNumber(?string $routingNumber): self
    {
        $this->routingNumber = $routingNumber;

        return $this;
    }
}
