<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Paylocity\Api\Model;

class StagedEmployeeCustomDropDownFieldsItem
{
    /**
     * The custom field category.  Acceptable value is 'PayrollAndHR'.
     *
     * @var string
     */
    protected $category;

    /**
     * The custom field category.  Acceptable value is 'PayrollAndHR'.
     */
    public function getCategory(): string
    {
        return $this->category;
    }

    /**
     * The custom field category.  Acceptable value is 'PayrollAndHR'.
     */
    public function setCategory(string $category): self
    {
        $this->category = $category;

        return $this;
    }
}
