<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Paylocity\Api\Model;

class StagedEmployeeWebTime
{
    /**
     * Badge number usually issued for time and attendance system use. <br  />Max length: 50.
     *
     * @var string|null
     */
    protected $badgeNumber;
    /**
     * Rate to be charged to third party for time worked by the employee. It is most commonly referenced in the Cost Center Charge, Cost Center Charge vs. Cost Reports, and the Customer Invoice time and attendance reports. <br  />Decimal (12,2).
     *
     * @var float|null
     */
    protected $chargeRate;
    /**
     * If set to true, changes to employee data will be reflected in Web Time.
     *
     * @var bool|null
     */
    protected $isTimeLaborEnabled;

    /**
     * Badge number usually issued for time and attendance system use. <br  />Max length: 50.
     */
    public function getBadgeNumber(): ?string
    {
        return $this->badgeNumber;
    }

    /**
     * Badge number usually issued for time and attendance system use. <br  />Max length: 50.
     */
    public function setBadgeNumber(?string $badgeNumber): self
    {
        $this->badgeNumber = $badgeNumber;

        return $this;
    }

    /**
     * Rate to be charged to third party for time worked by the employee. It is most commonly referenced in the Cost Center Charge, Cost Center Charge vs. Cost Reports, and the Customer Invoice time and attendance reports. <br  />Decimal (12,2).
     */
    public function getChargeRate(): ?float
    {
        return $this->chargeRate;
    }

    /**
     * Rate to be charged to third party for time worked by the employee. It is most commonly referenced in the Cost Center Charge, Cost Center Charge vs. Cost Reports, and the Customer Invoice time and attendance reports. <br  />Decimal (12,2).
     */
    public function setChargeRate(?float $chargeRate): self
    {
        $this->chargeRate = $chargeRate;

        return $this;
    }

    /**
     * If set to true, changes to employee data will be reflected in Web Time.
     */
    public function getIsTimeLaborEnabled(): ?bool
    {
        return $this->isTimeLaborEnabled;
    }

    /**
     * If set to true, changes to employee data will be reflected in Web Time.
     */
    public function setIsTimeLaborEnabled(?bool $isTimeLaborEnabled): self
    {
        $this->isTimeLaborEnabled = $isTimeLaborEnabled;

        return $this;
    }
}
