<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Paylocity\Api\Model;

class TrackingNumberResponse
{
    /**
     * The unique tracking number.
     *
     * @var string
     */
    protected $trackingNumber;

    /**
     * The unique tracking number.
     */
    public function getTrackingNumber(): string
    {
        return $this->trackingNumber;
    }

    /**
     * The unique tracking number.
     */
    public function setTrackingNumber(string $trackingNumber): self
    {
        $this->trackingNumber = $trackingNumber;

        return $this;
    }
}
